//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyeProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFactura
    {
        public int idDetalleFac { get; set; }
        public int idServProduc { get; set; }
        public string CantidadSoP { get; set; }
        public decimal PrecioTotal { get; set; }
        public int idEncabezadoFac { get; set; }
    
        public virtual ServicioOProducto ServicioOProducto { get; set; }
        public virtual EncabezadoFactura EncabezadoFactura1 { get; set; }
    }
}
