//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyeProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicioOProducto
    {
        public ServicioOProducto()
        {
            this.DetalleFactura = new HashSet<DetalleFactura>();
        }
    
        public int idServProduc { get; set; }
        public string Codigo { get; set; }
        public string Precio { get; set; }
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<DetalleFactura> DetalleFactura { get; set; }
    }
}
