//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyeProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposVehiculos
    {
        public TiposVehiculos()
        {
            this.Vehiculos = new HashSet<Vehiculos>();
        }
    
        public int idTipoVehiculo { get; set; }
        public string Código { get; set; }
        public string Tipo { get; set; }
    
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
    }
}
