//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyeProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.EncabezadoFactura = new HashSet<EncabezadoFactura>();
            this.Vehiculos = new HashSet<Vehiculos>();
        }
    
        public int idUsuario { get; set; }
        public int Cedula { get; set; }
        public string Genero { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Nombre { get; set; }
        public string Apellido1 { get; set; }
        public string Apellido2 { get; set; }
        public string Correo { get; set; }
        public string TipoUsuario { get; set; }
        public int id_Provincia { get; set; }
        public int id_Canton { get; set; }
        public int id_Distrito { get; set; }
        public string Contrasenia { get; set; }
    
        public virtual Canton Canton { get; set; }
        public virtual Distrito Distrito { get; set; }
        public virtual ICollection<EncabezadoFactura> EncabezadoFactura { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
    }
}
