//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyeProgra6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public Vehiculos()
        {
            this.EncabezadoFactura = new HashSet<EncabezadoFactura>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int idVehiculo { get; set; }
        public string Placa { get; set; }
        public int NumeroPuertas { get; set; }
        public int NumeroRuedas { get; set; }
        public int idMarcaVehiculos { get; set; }
        public int idTipoVehiculo { get; set; }
    
        public virtual ICollection<EncabezadoFactura> EncabezadoFactura { get; set; }
        public virtual MarcaVehiculos MarcaVehiculos { get; set; }
        public virtual TiposVehiculos TiposVehiculos { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
